### ISSUE TITLE
Regarding Updation

### ISSUE THREAD

**Issue by PartapSBimrah** [the-dagger/MLKitAndroid#1]
Hello Sir,

The app is really good. And Three functional not working like **Text Machine Learning**, **Building Machine Learning**, **Bar Code Machine Learning** not working properly and show a message that "Still working". So please solve this issues and update project. 

Cheers,

**Comment by the-dagger** [comment]
Hey @IamKanwarpartapSingh 
Yep, that's work in progress I'll update it soon!

**Comment by PartapSBimrah** [comment]
Whenever you will be updated then let me know on or alert me via Github.

**Comment by the-dagger** [comment]
All the features minus face detection have been added.
I will probably add face detection with a custom model, so closing this now.
